### ISSUE TITLE
Help in completion setup

### ISSUE THREAD

**Issue by statquant** [neoclide/coc-r-lsp#11]
Hello first many thanks for this plugin, it "just works" in vim as opposed to so many other I've tried.
I have question about the setup of completion

**As I type completion for parameters**

Say I want to type `fread(file = "stuff")`
When I type `fre` I directly get the suggestion of `fread`, then when I reach `fread(` I get the info of `fread` while I really would like to see the parameters

I get this
![image](https://user-images.githubusercontent.com/3612473/85950554-5d7c3000-b955-11ea-9e48-84d4f4ff4107.png)

I wish I could get this:
![image](https://user-images.githubusercontent.com/3612473/85950530-39205380-b955-11ea-94ed-742762ef0700.png)

Is it possible to get this behaviour (note that it's not bad because I get parameters by pressing `fread(<tab>` ?

**Chaining parameters completion**

This is more annoying, say I want `fread(file = "stuff", n = 1)`, when I reach `fread(file = "stuff"` I can only get the completion using `<tab>` again after a comma ie: `fread(file = "stuff",<tab>)` I cannot get it with `, ` (`<comma><space>`) (it is considered best practice to have spaces after comma) ie: `fread(file = "stuff", <tab>)` (notice the space)

See an example
![image](https://user-images.githubusercontent.com/3612473/85950721-72a58e80-b956-11ea-99b9-fff3b04a2fb0.png)

**Completion of column names in `data.frame` and `data.table`**

I did not succeed in getting column name completions for `data.frame` after `$` or for data.tables after `DT[, .(`
Is it possible

Many thanks and regards
Is it possible to get this behaviour, the only way I get completion after `, ` is to press `<c-x><c-o>`

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
The completion and signature trigger characters are comes from language server.
