### ISSUE TITLE
Update codebase

### ISSUE THREAD

**Issue by inventionate** [neoclide/coc-r-lsp#14]
vscode-r-lsp has recently received a major improvement and now supports, among other things, the automatic loading of packages in projects, e. g. https://github.com/REditorSupport/languageserver/issues/290. Is an update/adjustment of the versions planned? 

Thanks for the great Vim plugins!

**Comment by renkun-ken** [comment]
Also, the R language server must be started from project folder as the working directory to make it work, which is done by https://github.com/REditorSupport/vscode-r-lsp/pull/45.

**Comment by chemzqm** [comment]
Upgrade to 1.2.0
