### ISSUE TITLE
how to use this for R code completion?

### ISSUE THREAD

**Issue by ssh352** [neoclide/coc-r-lsp#2]
I've installed coc-r-lsp per the doc. 

I expect available methods will pop up when I type in the following code just like coc-python.  Please advise. 

```
library(data.table)
data.table.
```

**Comment by chemzqm** [comment]
Check out https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by ssh352** [comment]
<img width="333" alt="Screen Shot 2019-06-17 at 9 33 14 AM" src="https://user-images.githubusercontent.com/41779116/59572937-f7729100-90e2-11e9-8436-9c0385ee6e8a.png">

my bad, it already works. Bad example. Thanks.
