### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by fxi** [neoclide/coc-r-lsp#29]
Hi !

Not sure at which level this is handled, but it's quite confusing. Is it even a behavior from CoC or the LSP plugin ?

When I'm writing stuff, the correct completion is shown, but after a split second, random item does appear and I select the wrong item. 

For example : I want to select `inputHfId`, but `inAnyInterval` is shown.
![am_lsp_choice_m](https://user-images.githubusercontent.com/1196833/159286565-83536213-35cc-442e-911e-31ae71fee036.gif)

Thanks !

**Comment by chemzqm** [comment]
It's expected because the result from language server have higher priority

**Comment by fxi** [comment]
The issue is more about the small delay.  If I type fast, almost each time, I select the wrong item from the list. 

Exemple:
- I type some code
- The list does appear with the expected completion item. e.g. position 3.
- I navigate to it : 2 x press down key
- When I select the item, a new list appear from the LS with unrelated items. 

Possible solution: do not display the list until everything is fully resolved. The layout shift could be prevented.

However.. Using coc-tabnine, with priority set to 1000, I think I get better result.

In any case, it seems unrelated to coc-r-lsp and more like a behavior from coc itself and the latency of the language server.

Thanks :)

**Comment by chemzqm** [comment]
It's because the completion is refreshed after 200ms https://github.com/neoclide/coc.nvim/blob/master/src/completion/index.ts#L271, so no need to wait for slow source.
IMO, the language server need improved to response faster or return better results on such case.
