### ISSUE TITLE
neovim freezes with warning: source r timeout after 2000ms

### ISSUE THREAD

**Issue by ssh352** [neoclide/coc-r-lsp#3]
<img width="211" alt="Screen Shot 2019-08-21 at 10 15 28 AM" src="https://user-images.githubusercontent.com/41779116/63397331-cec98900-c3fc-11e9-8c6a-9870416c5004.png">

<img width="254" alt="Screen Shot 2019-08-21 at 2 03 44 PM" src="https://user-images.githubusercontent.com/41779116/63406470-92a62080-c41c-11e9-9516-8328478ffb26.png">

Usually after a :w on a R script, neovim  freezes multiple seconds with this warning and recovers afterwards. I also noticed a node process using a cpu core 100% during the freeze. Please advise, Thanks!

**Comment by ssh352** [comment]
there must be a regression somewhere
I reverted coc.nvim to b96f1d0e0b06f578416c8684af1b59af8d964d95 and it fixed it.

**Comment by ssh352** [comment]
<img width="309" alt="Screen Shot 2020-01-22 at 11 32 03 AM" src="https://user-images.githubusercontent.com/41779116/72863252-e211b500-3d0a-11ea-8e0e-6753a20fa9ad.png">

it happens after :w, and when there is a big text file opened in one buffer.

**Comment by chemzqm** [comment]
You need increase your timeout for suggest https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources.
