### ISSUE TITLE
Invalid response body while trying to fetch https://registry.npmjs.org/brace-expansion:

### ISSUE THREAD

**Issue by armonbc** [neoclide/coc-r-lsp#37]
2240 verbose node v18.12.1
2241 verbose npm  v8.19.2
2242 error code FETCH_ERROR
2243 error errno FETCH_ERROR
2244 error invalid json response body at https://registry.npmjs.org/brace-expansion reason: Invalid response body while trying to fetch https://registry.npmjs.org/brace-expansion: ENOENT: no such file or directory, rename '/home/xxx/.npm/_cacache/tmp/d5ac7a52' -> '/home/xxx/.npm/_cacache/content-v2/sha512/78/e6/50b4841499d640a6a6c0194624d1affc30e50be70d367ba69abcab602605c93d1a48306600edfd5b97cc454a778009b58a03c88ce845be80533f5a443b1f'

**Comment by mph-service** [comment]
Closed as solved

**Comment by armonbc** [comment]
Solved by client issue
